name: Flutter Build and Release APP

on:
  push:
    branches:
      - main
    tags:
      - '*'  # Trigger on all tags

jobs:
  build_and_release:
    name: Build, Upload, and Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3

      - name: Get dependencies
        run: flutter pub get

      - name: Check Formatting
        run: dart format --set-exit-if-changed lib test

      - name: Code Generation
        run: dart run build_runner build --delete-conflicting-outputs

      - name: Analyze code
        run: flutter analyze

      - name: Create env/keys.dev.json
        run: cp env/keys.example env/keys.dev.json

      - name: Build APK
        run: flutter build apk --flavor prod --target lib/main_prod.dart --dart-define-from-file env/keys.dev.json --release -vv

      - name: Upload APK as artifact
        uses: actions/upload-artifact@v3
        with:
          name: android-app
          path: build/app/outputs/flutter-apk/app-prod-release.apk # Update path if needed

